core-image-sato: Add x11 as required feature.
Even though x11 is currently a default DISTRO feature, even for
nodistro, core-image-sato should require the x11 feature. Without the
x11 in DISTRO_FEATURES, bitbake fails with the following:

ERROR: Required build target 'core-image-sato' has no buildable providers.
Missing or unbuildable dependency chain was: ['core-image-sato',
'packagegroup-core-x11-base']

With this change, the error changes to something more clear to new
users of the project:

ERROR: Nothing PROVIDES 'core-image-sato'
core-image-sato was skipped: missing required distro feature 'x11'
(not in DISTRO_FEATURES)

(From OE-Core rev: 7de7e86393f208dfb3a5708a16a67faff9683a79)

Signed-off-by: Walter Werner SCHNEIDER <contact@schnwalter.eu>
Signed-off-by: Mathieu Dubois-Briand <mathieu.dubois-briand@bootlin.com>
Signed-off-by: Richard Purdie <richard.purdie@linuxfoundation.org>